CREATE DATABASE IF NOT EXISTS projectmvp CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE projectmvp;
CREATE TABLE IF NOT EXISTS hibak (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nev VARCHAR(100) DEFAULT 'Névtelen',
  eszkoz VARCHAR(200),
  leiras TEXT,
  status VARCHAR(50) DEFAULT 'uj',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
